---
groups:
- name: nats-release
  jobs:
  - deploy-nats-standalone
  - smoke-tests
  - delete-nats-standalone
  - deploy-cf-with-created-nats
  - cf-acceptance-tests
  - delete-cf-deployment
  - create-final-release
- name: maintenance
  jobs:
  - nats-setup
  - nats-destroy
- name: bump-go
  jobs:
  - upgrade-go1.x

resources:
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent

- name: golang-release-latest
  type: git
  source:
    branch: master
    tag_filter: v*
    uri: https://github.com/bosh-packages/golang-release.git

- name: nats-release
  type: git
  source:
    ignore_paths:
      - .final_builds/**
      - config/**
      - releases/**
      - ci
    branch: develop
    private_key: ((read_write_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: nats-release-ci
  type: git
  source:
    paths:
      - ci
    branch: develop
    private_key: ((read_write_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: nats-release-master
  type: git
  source:
    branch: master
    private_key: ((read_write_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: deployments-routing
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/deployments-routing.git

- name: networking-oss-deployments
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: networking-oss-tools
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-tools.git


- name: we-dont-use-vars-files
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: bosh-bootloader
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-bootloader

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v8.*

- name: morning-trigger
  type: time
  source:
    location: America/Los_Angeles
    start: 6:00 AM
    stop: 6:01 AM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: evening-trigger
  type: time
  source:
    location: America/Los_Angeles
    start: 7:00 PM
    stop: 7:01 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
- name: upgrade-go1.x
  plan:
  - in_parallel:
    - get: nats-release
    - get: golang-release-latest
      trigger: true
    - get: nats-release-ci
  - task: upgrade
    file: nats-release-ci/ci/tasks/upgrade-package-in-release/task.yml
    params:
      RELEASE: release
      PACKAGE: golang-1-linux
      BRANCH: develop
      GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp_nats_blobstore_service_account_key))
    input_mapping:
      release: nats-release
      package-release: golang-release-latest
  - task: save-golang-version-to-file
    file: nats-release-ci/ci/tasks/save-golang-version-to-file/task.yml
    params:
      BRANCH: develop
    input_mapping:
      release: modified-release
  - put: nats-release
    params:
      repository: modified-release

- name: nats-setup
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: nats-release-ci
    - get: bosh-bootloader
    - get: morning-trigger
      trigger: true
  - task: add-parent-dns
    file: nats-release-ci/ci/tasks/add-parent-dns/task.yml
    params:
      ENVIRONMENT: nats-env
    input_mapping:
      bbl-state: networking-oss-deployments
  - task: make-certs
    file: nats-release-ci/ci/tasks/make-certs/task.yml
    params:
      ENVIRONMENT: nats-env
    input_mapping:
      bbl-state: updated-bbl-state
  - task: setup-nats
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
      BBL_GCP_REGION: us-west1
      BBL_LB_CERT: ../lb_certs/cert.pem
      BBL_LB_KEY: ../lb_certs/key.pem
      LB_DOMAIN: nats-env.routing.cf-app.com
      BBL_ENV_NAME: nats-env
      BBL_STATE_DIR: environments/nats-env/bbl-state
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
    input_mapping:
      bbl-config: updated-bbl-state
      bbl-state: updated-bbl-state
    ensure:
      put: networking-oss-deployments
      params:
        repository: updated-bbl-state
        rebase: true

- name: nats-destroy
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: cf-deployment-concourse-tasks
    - get: evening-trigger
      passed:
      - delete-cf-deployment
      - delete-nats-standalone
      trigger: true
  - task: destroy-nats-env
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
    input_mapping:
      bbl-state: networking-oss-deployments
    ensure:
      put: networking-oss-deployments
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-nats-standalone
  serial_groups: [nats]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: stemcell
      trigger: true
    - get: nats-release
      trigger: true
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: nats-release-ci
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: morning-trigger
      trigger: true
      passed: [nats-setup]
  - task: deploy-nats
    file: nats-release-ci/ci/tasks/bosh-deploy-nats/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: smoke-tests
  public: true
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release
      passed: [deploy-nats-standalone]
      trigger: true
    - get: nats-release-ci
    - get: networking-oss-deployments
      passed: [deploy-nats-standalone]
    - get: networking-oss-tools
    - get: cf-deployment-concourse-tasks
  - task: run-errand-smoke-tests
    file: nats-release-ci/ci/tasks/run-errand-nats-release/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      DEPLOYMENT_NAME: nats
      ERRAND_NAME: smoke-tests
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: delete-nats-standalone
  public: true
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: nats-release
      trigger: true
      passed: [smoke-tests]
    - get: evening-trigger
      trigger: true
  - task: delete-nats-standalone
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      DEPLOYMENT_NAME: nats
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: deploy-cf-with-created-nats
  serial_groups: [nats]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: nats-release
      trigger: true
      passed: [smoke-tests]
    - get: morning-trigger
      trigger: true
      passed: [nats-setup]
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
  - task: deploy-cf-with-created-nats
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
      release: nats-release
      ops-files: cf-deployment
      vars-files: we-dont-use-vars-files
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
      SYSTEM_DOMAIN: nats-env.routing.cf-app.com
      OPS_FILES: |
        operations/use-internal-lookup-for-route-services.yml
  - task: run-bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: cf-acceptance-tests
  serial_groups: [nats]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
    - get: cf-acceptance-tests
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: cf-deployment-concourse-tasks
    - get: nats-release
      passed: [deploy-cf-with-created-nats]
      trigger: true
  - task: create-integration-config
    file: nats-release-ci/ci/tasks/create-integration-configs/task.yml
    params:
      ENVIRONMENT: nats-env
      ENABLE_ISOLATION_SEGMENT_TESTS: false
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
      integration-configs: created-integration-configs
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
      CATS_INTEGRATION_CONFIG_FILE: nats-env/cats_integration_config.json
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-cats
    input_mapping:
      integration-config: updated-integration-configs
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json

- name: delete-cf-deployment
  public: true
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
    - get: cf-deployment-concourse-tasks
    - get: networking-oss-deployments
    - get: networking-oss-tools
    - get: nats-release
      trigger: true
      passed: [cf-acceptance-tests]
    - get: evening-trigger
      trigger: true
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      DEPLOYMENT_NAME: cf
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: create-final-release
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
    - get: nats-release
      passed: [cf-acceptance-tests]
    - get: nats-release-master
  - task: create-final-release
    file: nats-release-ci/ci/tasks/create-final-nats-release/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
    params:
      RELEASE_NAME: nats
      GCP_NATS_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp_nats_blobstore_service_account_key))
  - put: nats-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - task: merge-master-into-develop
    file: nats-release-ci/ci/tasks/merge-nats-release-master-into-develop/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
  - put: nats-release
    params:
      repository: final-release-repo
