---
groups:
- name: nats-release
  jobs:
  - deploy-cf-with-created-nats
  - smoke-tests
  - cf-acceptance-tests
  - delete-cf-deployment
  - smoke-tests-and-CATs
  - create-final-release
- name: maintenance
  jobs:
  - nats-setup
  - nats-destroy
- name: bump-go
  jobs:
  - upgrade-go1.x

resources:
- name: golang-release-latest
  type: git
  source:
    branch: master
    tag_filter: v*
    uri: https://github.com/bosh-packages/golang-release.git

- name: nats-release
  type: git
  source:
    ignore_paths:
      - .final_builds/**
      - config/**
      - releases/**
      - ci
    branch: develop
    private_key: ((read_write_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: nats-release-ci
  type: git
  source:
    paths:
      - ci
    branch: develop
    private_key: ((read_write_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: routing-release-ci
  type: git
  source:
    paths:
      - ci/tasks
    branch: develop
    uri: https://github.com/cloudfoundry/routing-release

- name: nats-release-master
  type: git
  source:
    branch: master
    private_key: ((read_write_deploy_key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: networking-oss-deployments
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: we-dont-use-vars-files
  type: git
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: bosh-bootloader
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-bootloader

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v10.*

- name: morning-trigger
  type: time
  source:
    location: America/Los_Angeles
    start: 6:00 AM
    stop: 6:01 AM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: evening-trigger
  type: time
  source:
    location: America/Los_Angeles
    start: 7:00 PM
    stop: 7:01 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: weekly
  type: time
  icon: clock
  source:
    interval: '168h'  # 1 week

jobs:
- name: upgrade-go1.x
  plan:
  - in_parallel:
    - get: nats-release
    - get: golang-release-latest
      trigger: true
    - get: nats-release-ci
  - task: upgrade
    file: nats-release-ci/ci/tasks/upgrade-package-in-release/task.yml
    params:
      RELEASE: release
      PACKAGE: golang-1-linux
      BRANCH: develop
      GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp_nats_blobstore_service_account_key))
    input_mapping:
      release: nats-release
      package-release: golang-release-latest
  - task: save-golang-version-to-file
    file: nats-release-ci/ci/tasks/save-golang-version-to-file/task.yml
    params:
      BRANCH: develop
    input_mapping:
      release: modified-release
  - put: nats-release
    params:
      repository: modified-release

- name: nats-setup
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: networking-oss-deployments
    - get: nats-release-ci
    - get: bosh-bootloader
    - get: morning-trigger
      trigger: true
  - task: add-parent-dns
    file: nats-release-ci/ci/tasks/add-parent-dns/task.yml
    params:
      ENVIRONMENT: environments/nats-env
    input_mapping:
      bbl-state: networking-oss-deployments
  - task: make-certs
    file: nats-release-ci/ci/tasks/make-certs/task.yml
    params:
      ENVIRONMENT: nats-env
      ENV_PATH: environments/nats-env
    input_mapping:
      bbl-state: updated-bbl-state
  - task: setup-nats
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
      BBL_GCP_REGION: us-west1
      BBL_LB_CERT: ../lb_certs/cert.pem
      BBL_LB_KEY: ../lb_certs/key.pem
      LB_DOMAIN: nats-env.routing.cf-app.com
      BBL_ENV_NAME: nats-env
      BBL_STATE_DIR: environments/nats-env/bbl-state
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
    input_mapping:
      bbl-config: updated-bbl-state
      bbl-state: updated-bbl-state
    ensure:
      put: networking-oss-deployments
      params:
        repository: updated-bbl-state
        rebase: true

- name: nats-destroy
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: networking-oss-deployments
    - get: cf-deployment-concourse-tasks
    - get: evening-trigger
      passed:
      - delete-cf-deployment
      trigger: true
  - task: destroy-nats-env
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
    input_mapping:
      bbl-state: networking-oss-deployments
    ensure:
      put: networking-oss-deployments
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-cf-with-created-nats
  serial_groups: [nats]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: networking-oss-deployments
    - get: we-dont-use-vars-files
    - get: nats-release
      trigger: true
    - get: morning-trigger
      trigger: true
      passed: [nats-setup]
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
  - task: deploy-cf-with-created-nats
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
      release: nats-release
      ops-files: nats-release
      vars-files: we-dont-use-vars-files
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
      SYSTEM_DOMAIN: nats-env.routing.cf-app.com
      OPS_FILES: |
        example-manifests/ops-files/enable_nats_tls_for_cf.yml
  - task: run-bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: smoke-tests-and-CATs
  plan:
  - in_parallel:
    - do:
      - get: routing-release-ci
        params: {submodules: none}
      - task: claim-cf-deployment-environment
        file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
        tags:
        - vsphere-cf-networking
        params:
          ENVIRONMENT_TYPE: cf-deployment
          ENVIRONMENT_NOTES: nats-cf-deployment-cats
          TOOLSMITHS_API_TOKEN: ((toolsmiths_api_key))
    - get: cf-acceptance-tests
    - get: nats-release-ci
    - get: networking-oss-deployments
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: nats-release
    - get: we-dont-use-vars-files
      trigger: true
    - get: weekly
      trigger: true
  - task: write-lb-cert-to-credhub
    file: routing-release-ci/ci/tasks/write-lb-cert-to-credhub/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: nats-release
    params:
      SOURCE1_DIR: example-manifests/ops-files
  - task: fetch-our-envs-manifest
    file: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: redeploy-nats-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: nats-release
      ops-files: merged-operations
      vars-files: we-dont-use-vars-files
      cf-deployment: our-envs-manifest
    params:
      MANIFEST_FILE: manifest.yml
      OPS_FILES: |
        enable_nats_tls_for_cf.yml
        add-lb-ca-cert.yml
        use-compiled-releases.yml
        scale-for-cats.yml
        smoke-tests.yml
  - task: run-smoke-tests
    file: nats-release-ci/ci/tasks/run-errand-nats-release/task.yml
    params:
      DEPLOYMENT_NAME: cf
      ERRAND_NAME: smoke-tests
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: create-integration-config
    file: nats-release-ci/ci/tasks/create-integration-configs/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
    params:
      ENABLE_ISOLATION_SEGMENT_TESTS: false
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      integration-configs: created-integration-configs
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats_integration_config.json
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-cats
    input_mapping:
      integration-config: updated-integration-configs
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      TOOLSMITHS_API_TOKEN: ((toolsmiths_api_key))

- name: smoke-tests
  public: true
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release
      passed: [deploy-cf-with-created-nats]
      trigger: true
    - get: nats-release-ci
    - get: networking-oss-deployments
    - get: cf-deployment-concourse-tasks
  - task: run-errand-smoke-tests
    file: nats-release-ci/ci/tasks/run-errand-nats-release/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      DEPLOYMENT_NAME: cf
      ERRAND_NAME: smoke-tests
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: cf-acceptance-tests
  serial_groups: [nats]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
    - get: cf-acceptance-tests
    - get: networking-oss-deployments
    - get: cf-deployment-concourse-tasks
    - get: nats-release
      passed: [smoke-tests]
      trigger: true
  - task: create-integration-config
    file: nats-release-ci/ci/tasks/create-integration-configs/task.yml
    params:
      ENVIRONMENT: nats-env
      ENABLE_ISOLATION_SEGMENT_TESTS: false
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
      integration-configs: created-integration-configs
    params:
      BBL_STATE_DIR: environments/nats-env/bbl-state
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-cats
    input_mapping:
      integration-config: updated-integration-configs
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json

- name: delete-cf-deployment
  public: true
  serial_groups: [nats]
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
    - get: cf-deployment-concourse-tasks
    - get: networking-oss-deployments
    - get: nats-release
      trigger: true
      passed: [cf-acceptance-tests]
    - get: evening-trigger
      trigger: true
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: networking-oss-deployments
    params:
      DEPLOYMENT_NAME: cf
      BBL_STATE_DIR: environments/nats-env/bbl-state

- name: create-final-release
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
    - get: nats-release
      passed: [cf-acceptance-tests]
    - get: nats-release-master
  - task: create-final-release
    file: nats-release-ci/ci/tasks/create-final-nats-release/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
    params:
      RELEASE_NAME: nats
      GCP_NATS_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp_nats_blobstore_service_account_key))
  - put: nats-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - task: merge-master-into-develop
    file: nats-release-ci/ci/tasks/merge-nats-release-master-into-develop/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
  - put: nats-release
    params:
      repository: final-release-repo
