---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: toolsmiths-metadata-dir
- name: nats-release-ci
- name: networking-oss-deployments

run:
  path: nats-release-ci/ci/tasks/run-errand-nats-release/task

params:
  DEPLOYMENT_NAME: cf
  ERRAND_NAME:
